name: Proposer une amélioration
description: Expliquer un besoin et une solution possible.
title: "[Idée] "
body:
  - type: textarea
    id: need
    attributes:
      label: Quel problème souhaitez-vous résoudre ?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Solution proposée
      description: Décrivez le comportement souhaité, avec un exemple si possible.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives envisagées
